### ISSUE TITLE
Migration script

### ISSUE THREAD

**Issue by thatoddmailbox** [MyHomeworkSpace/api-server#1]
There needs to be a script to migrate data from the old database format to the new one. It should:
- be written in Go
- be well tested (try a migration of `staging2` before?)
- not take forever, but speed isn't _that_ important (the migration can happen when not many people are using it)
- not break things

**Comment by willbarkoff** [comment]
We can put up a scheduled downtime announcement for something like 2am-4am and then we have 2 hours to run the script in case something goes wrong.

**Comment by thatoddmailbox** [comment]
@nywillb I don't want to and also probably can't stay up until 2-3am...

**Comment by willbarkoff** [comment]
@thatoddmailbox can't you write a script that will autorun at 2am? You can use task scheduler right?

**Comment by thatoddmailbox** [comment]
@nywillb but if something goes wrong?

**Comment by thatoddmailbox** [comment]
This has been done, and we have actually migrated.
